### ISSUE TITLE
不能正确处理列表中的展开框

### ISSUE THREAD

**Issue by leoleoasd** [OI-wiki/OI-Wiki-export#1]
如题
![image](https://user-images.githubusercontent.com/37735580/102204120-67deb600-3f04-11eb-8a45-3bdbad757da6.png)
![image](https://user-images.githubusercontent.com/37735580/102204152-7200b480-3f04-11eb-8339-1b2e007c4f2d.png)

**Comment by Enter-tainer** [comment]
感觉原文有点小问题，这个折叠框里面为什么会有代码块

**Comment by leoleoasd** [comment]
@Enter-tainer

**Comment by Enter-tainer** [comment]
目前看起来解决了很多 暂时close
