### ISSUE TITLE
add PDF版本将链接显示为脚注

### ISSUE THREAD

**Issue by xkww3n** [OI-wiki/OI-Wiki-export#10]
## 我遇到的问题是
目前，OI-wiki导出的PDF依然保留了「可点击链接」这一形式，而这些链接经打印后，将完全失效，无法知道这些链接指向何处。

## 我希望能有这样的解决方案
PDF生成工具在导出时，将链接转换成每一页的脚注形式。

**Comment by Enter-tainer** [comment]
我在实现这个功能的时候遇到了一些问题，对于链接，如果仅仅是将其对应的url填入脚注，体验看起来并不是很好？

毕竟在纸质的东西上面写 url 本身就感觉有点很奇怪...不知道你是怎么考虑这个功能的

**Comment by Enter-tainer** [comment]
https://mirror-hk.koddos.net/CTAN/macros/latex/contrib/qrcode/qrcode.pdf

**Comment by xkww3n** [comment]
> 我在实现这个功能的时候遇到了一些问题，对于链接，如果仅仅是将其对应的url填入脚注，体验看起来并不是很好？
> 
> 毕竟在纸质的东西上面写 url 本身就感觉有点很奇怪...不知道你是怎么考虑这个功能的

emmm...那也是没办法的事情吧？也许可以试试把url全部写到导出文件的末尾，自称一章，类似于一些书末的“参考文献”形式？

**Comment by Ir1d** [comment]
脑洞：内链写跳转页码，外链变二维码

**Comment by Enter-tainer** [comment]
done in #19
