### ISSUE TITLE
数学字体设置有误

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-Wiki-export#12]
数学公式中的直体不应该是 roboto
![Screenshot_2021-04-11-13-06-47-924_cn.wps.moffice_eng.jpg](https://user-images.githubusercontent.com/25521218/114293222-f20be500-9ac6-11eb-88cd-6d3fccb97216.jpg)

**Comment by SharzyL** [comment]
上游的锅，作者这里把数学公式放在了 `行内代码` 里面了：

https://github.com/OI-wiki/OI-wiki/blob/e45ded29e861a5a218b9e39e7e50a2606aa0a3c9/docs/math/mobius.md#L115

不过数学公式字体确实需要改一下，不能 Noto Serif 和 CMU Serif 混用，可以在 oi-wiki-export.tex 里加这么两行代码

```tex
\setmathrm{CMU Serif}
\setmathsf{CMU Sans Serif}
```
