### ISSUE TITLE
[bug] content tabs support

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-Wiki-export#33]
如 [Release v20221218_0916](https://github.com/OI-wiki/OI-Wiki-export/releases/download/v20221218_0916/OI-wiki.pdf) 的 P519

**Comment by Tiphereth-A** [comment]
图

![](https://user-images.githubusercontent.com/62847935/209512325-d40d83dd-bc18-48b7-b724-c39fef3ff28d.png)

**Comment by diauweb** [comment]
workaround
```js

const pruneFields = ['=== "']
  ast.children = ast.children.filter(e => {
    if (e.type !== 'paragraph') return true
    const str = toString(e)
    for (const field of pruneFields) {
      if (str.startsWith(field)) return false
    }
    return true
})

visit(ast, 'code', function(node, _index, _parent) {
      if (node.value.startsWith('```') && node.value.endsWith('```') && node.lang === null) {
        const cb = node.value.split('\n')
        node.value = cb.slice(1, -1).join('\n')
        node.lang = cb[0].slice(3)
      }
})
```

**Comment by Enter-tainer** [comment]
https://github.com/OI-wiki/remark-tabbed @shawlleyw

**Comment by lycorisor** [comment]
请问这个问题为什么一直没有被修复，pdf看的不会很不整齐吗

**Comment by Enter-tainer** [comment]
@lycorisor 这个是今年ospp的项目，负责的大哥这几天比较忙，但是近期会修掉 🙏🙏

**Comment by Enter-tainer** [comment]
typst导出现已支持，latex的还在施工 
<img width="614" alt="image" src="https://github.com/OI-wiki/OI-Wiki-export/assets/25521218/02899bec-e961-42b1-8efe-986ff990abc6">
