### ISSUE TITLE
有没有已经做好的 PDF，发一份给我谢谢

### ISSUE THREAD

**Issue by Zaoly** [OI-wiki/OI-Wiki-export#37]
（伸手党）

**Comment by Enter-tainer** [comment]
<img width="721" alt="image" src="https://github.com/OI-wiki/OI-Wiki-export/assets/25521218/2a7496a0-ddcc-43df-9d94-9ecca2df3612">

**Comment by Enter-tainer** [comment]
不过ci确实挂了几周，目前只有旧一点的
