### ISSUE TITLE
[bug] 页码奇偶错误

### ISSUE THREAD

**Issue by YouXam** [OI-wiki/OI-Wiki-export#47]
在生成的PDF版本中，（假设打印后摊开某一页）左侧页面的页码为奇数，右侧页面的页码为偶数。根据传统的打印和排版习惯，这应该是相反的：左侧页面应该是偶数，右侧页面应该是奇数。

因为页码的位置在左上角或者右上角，所以这个问题不能简单的使用添加或删除空白页来修复，需要同时调整每一页的页码位置。

注：一般来讲，第一页会放在第一页纸的第一面。

现在的情况：

![image](https://github.com/OI-wiki/OI-Wiki-export/assets/49866772/4c6390fb-e0d7-4d89-87c9-afdc5fa8f757)

期望的情况：

![image](https://github.com/OI-wiki/OI-Wiki-export/assets/49866772/ac57777d-b22e-4734-97cd-dfe84c9812ba)

**Comment by Enter-tainer** [comment]
这是typst版的？

**Comment by Enter-tainer** [comment]
我想这个是两个问题

1. 如果页码在左边，那么页码应该是偶数
2. 需要加一些空白页，把页码为1的页padding到一张纸的正面

**Comment by YouXam** [comment]
> 我想这个是两个问题
> 
> 1. 如果页码在左边，那么页码应该是偶数
> 2. 需要加一些空白页，把页码为1的页padding到一张纸的正面

是的

**Comment by Enter-tainer** [comment]
ok 应该是模板需要调整一下 cc @megakite
