### ISSUE TITLE
[bug] 块嵌套时处理异常

### ISSUE THREAD

**Issue by awerty-noob** [OI-wiki/OI-Wiki-export#70]
官方release的14.4有大量的文字在代码块里，导致输出不正确。以下是pdf与原网页对比：
![image](https://github.com/OI-wiki/OI-Wiki-export/assets/36948728/9fd7cc32-64c1-4f59-9bd2-ea197a1b7900)
![image](https://github.com/OI-wiki/OI-Wiki-export/assets/36948728/a7fcd62a-dcb0-4b66-85e9-1a1cea551f44)

**Comment by Enter-tainer** [comment]
@awerty-noob 可以发一下对应的页面链接吗？方便排查问题

**Comment by awerty-noob** [comment]
https://oiwiki.org/topic/segment-tree-offline/

**Comment by Enter-tainer** [comment]
排查之后，发现是这个页面的写法有问题，export本身没有bug，我会在 OI-wiki/Oi-wiki 里面开一个pr修复
